### PR TITLE
1842 Dataset Dialog - properties editing update

### PR DESCRIPTION
**Pull request by dk1844**
As outlined in #1842, a longer dataset property name may have previously been cut off and the user was unable to reach the whole string.

## Solution
The dialog has undergone several changes to address the problem at hand, namely:
 - width of the value field has been slightly decreased (the values from the selection will be fully visible when opened if smaller)
 - default width of the dialog has been set to 55em (sufficient in testing), but mainly, the dialog has been made stretchable -- so if the user wants to enlarge the dialog to have more space, they can
 - more sensible tooltip has been provided - revealing the full property name string and optionally the description if available -- thus, the user can read a very long property name this way, too, if ellipsized

(I have also attempted to diminish the blank space at the label's side, but I was unsuccessful in this regard 
- with the current `ResponsiveLayout`, it can be done using `layoutData.ResponsiveFlowLayoutData.weight, but then the labels are not aligned. 
- with `ResponsiveGridLayout`, it can be done as well quite nicely with `labelSpanM` settings, but the solution on the other hand warns to clash on sync/async calls in the console. Esthetically, this solution would look the best if no issues were involved.

## Showcase
Showing a resizable dialog with enhanced hints on the DS properties:
ds-props-resized-hints-resizable
Smaller width version (when resized) is also fully usable:
ds-props-smaller-display

## Release notes suggestion
Dataset properties editing UX has been enhanced - now, there is more room for the property name, a useful tooltip is provided and the dialog is resizable.

### CODE REVIEW

**Review by benedeki — CHANGES_REQUESTED** [review]
Please direct the PR towards `support/2.21` branch.
And eventually another PR into `hotfix/2.22`.

**Comment by benedeki** [comment]
There's definitely more space. 👍 
But I would create a box around the properties to distinguish them. And make all the edits same width and align with the other edits of the dataset (see the first two of the of the picture).
Having the labels aligned to left instead of right like of the "major" edits might stay, again as a distinguishing sign. 🤔 
image

**Comment by dk1844** [comment]
> There's definitely more space. 👍
> But I would create a box around the properties to distinguish them. And make all the edits same width and align with the other edits of the dataset (see the first two of the of the picture).
...

I have added a border around the properties list, usable for Small and Medium dialog sizing. The edits are aligned on my machine, so I am surprised that it does not work for you. They should be, could you please recheck with the latest commit?

ds-border-suggestion-wider
ds-border-suggestion

**Review by benedeki — DISMISSED** [review]
It needed a couple of (forced) refreshes and reloads - it now shows the edits aligned.
Thanks for the frame. I like it this way now. But please have it approved by somebody closer to users. 😉

**Comment by Zejnilovic** [comment]
Not critical but, the whole of the row is a popup for the name
Jul-13-2021 13-14-10

**Comment by dk1844** [comment]
> Not critical but, the whole of the row is a popup for the name
> Jul-13-2021 13-14-10

Yes, I know. However, I don't really know how to fix this, because you do not have code-access to the label object on the list. The code goes like this:
```xml
<List>
    <InputListItem tooltip="<tooltip for the row>">
        <HBox>
            <Input type="Text" /> <!-- string input, or: -->
            <Select /> <!-- choice input -->
            <Icon tooltip="<tooltip for the essentiality icon>" />
        </HBox>
    </InputListItem>
</List>
```

So I fear there is nowhere to specify that the row tooltip should actually be only assigned to the row label. The `InputListItem` takes this functionality from `Element`, so there is no necessary specialization to achieve this.

So unless we want to resort to some amazing stuff like [css tooltips](https://stackoverflow.com/questions/7117073/add-a-tooltip-to-a-div), I do not see a straightforward way to do it.

**Comment by dk1844** [comment]
Based on feedback (@zakera786, @aaishaosman), the Small size of the Dataset editing dialog has been made the default view (still resizable if the user needed):
DsEditsmallSizeDefault

**Comment by benedeki** [comment]
> 
> 
> Based on feedback (@zakera786, @aaishaosman), the Small size of the Dataset editing dialog has been made the default view (still resizable if the user needed):
> DsEditsmallSizeDefault

I guess, this justifies the PR: Tested label.

**Review by benedeki — APPROVED** [review]

**Pull request merged**
