### PR TITLE
#2151 Remove hardcoded spline from Enceladus

### LINKED ISSUE #2152: Remove Hardcoded Spline, use codeles init
## Background
To align with the planned practices, we should remove hardcoded dependency on other projects, even though they come from our own back yard. This allows us to release more often and independently.

Spline has a feature called codeless init. This is a perfect feature for this.

## Feature
- [ ] Remove Hardcoded spline from spark-jobs
- [ ] Replace Menas' Spline tab with a link
  - [ ] Link can be a directly to the lineage from specific run
- [ ] Add Spline codeless initialization in shell scripts

### PR DESCRIPTION
**Pull request by Zejnilovic**
Fixes #2152 

Release Notes: Remove HardCoded spline. Add options to bash scripts to run spline codeless.

### CODE REVIEW

**Review by jakipatryk — COMMENTED** [review]
I think the part of README:
> [**Spline UI deployment**](https://absaoss.github.io/spline/) - place the [spline.war](https://search.maven.org/remotecontent?filepath=za/co/absa/spline/spline-web/0.3.9/spline-web-0.3.9.war)
 in your Tomcat webapps directory (rename after downloading to _spline.war_); NB! don't forget to set up the `spline.mongodb.url` configuration for the _war_
[...]
The _Spline UI_ can be omitted; in such case the **REST API** `spline.urlTemplate` setting should be set to empty string. 

Is no longer relevant?

Checked the code, ran tests, checked UI.

**Comment by miroslavpojer** [comment]
- [ ] pulled
- [ ] test run
- [ ] code review
- [ ] hermes tests with spline - planned

**Review by benedeki — COMMENTED** [review]
Looks good.
Could `SplineReference` be removed too?

**Comment by Zejnilovic** [comment]
> Looks good. Could `SplineReference` be removed too?

It could. But the Spline reference has nothing to do with Spline. It is just the **destination folder** and **app id**. That is still good info. 

On the other hand, if I start toying with it, I would also have to look into MongoDB migration. 

I would touch on the data model with move PostgreSQL, not now.

What do you think?

**Comment by benedeki** [comment]
> > Looks good. Could `SplineReference` be removed too?
> 
> It could. But the Spline reference has nothing to do with Spline. It is just the **destination folder** and **app id**. That is still good info.
> 
> On the other hand, if I start toying with it, I would also have to look into MongoDB migration.
> 
> I would touch on the data model with move PostgreSQL, not now.
> 
> What do you think?

Fair enough 👍

**Review by dk1844 — APPROVED** [review]
LGTM (just read the code)

**Review by lsulak — APPROVED** [review]
LGTM, just read the code, pulled, and built.

**Pull request merged**
