### PR TITLE
169 Editing dataset with wrong paths in HDFS makes user change the path to root first

### PR DESCRIPTION
**Pull request by lokm01**
- Changed Text to Input component for manual entry
- Added better validation directly to the HDFS browser
- Changed valueState to Warning for invalid HDFS paths

### CODE REVIEW

**Comment by Zejnilovic** [comment]
## UI Comments
### 1. In the case of dataset only one message
If I have two hdfs fields both yet non-existing I get two confirmation messages. Can we make it just one?

### 2. A prompt asking if we want to continue
image

This prompt is not like the others. Can we use [DialogConfirm](https://sapui5.hana.ondemand.com/#/entity/sap.m.Dialog/sample/sap.m.sample.DialogConfirm) from sapUI5?

### 3. Location of the text field and hdfs browser
What about moving the text field above the hdfs browser? I thought we agreed on this earlier. Is there an issue with it?

**Comment by GeorgiChochov** [comment]
I'm being nitpicky but our convention is for the branch name to be something like `bugfix/169-hdfs-browser-invalid-path`

**Comment by lokm01** [comment]
> I'm being nitpicky but our convention is for the branch name to be something like `bugfix/169-hdfs-browser-invalid-path` (just for future reference)

Sure..

**Comment by lokm01** [comment]
Sorry, closed this accidentally

**Comment by lokm01** [comment]
> ## UI Comments
> ### 1. In the case of dataset only one message
> If I have two hdfs fields both yet non-existing I get two confirmation messages. Can we make it just one?
> 
> ### 2. A prompt asking if we want to continue
> image
> 
> This prompt is not like the others. Can we use [DialogConfirm](https://sapui5.hana.ondemand.com/#/entity/sap.m.Dialog/sample/sap.m.sample.DialogConfirm) from sapUI5?
> 
> ### 3. Location of the text field and hdfs browser
> What about moving the text field above the hdfs browser? I thought we agreed on this earlier. Is there an issue with it?

1. Ok, will only trigger one confirm message (if the first one is cancelled). I believe the second one is still reasonable if the second path is invalid as well and the user confirms the first one. Thoughts?

2. Unless we rewrite the validations, I need a blocking confirmation dialog. Let's move this to a separate issue

3. That's still the plan, wanna do it in a separate PR

**Comment by lokm01** [comment]
Raised isssue #330 for 2)

**Comment by lokm01** [comment]
Raised #331 for 3)

**Pull request merged**
