### PR TITLE
#1538 postProcessing reread output - normalization

### PR DESCRIPTION
**Pull request by dk1844**
This change directly addresses #1538 - now both `process*Result` methods return `Unit` and thus make any further post-processing routines to reload data from FS as originally intended. (i.e. prohibit using "returned" dataframe to be used)

The rereading is deliberate to ensure that the same data that is being post-processed are already written to the output location and the postProcessing could not be affected by any kind of plan-rerun that could result in newly computed data (this is especially a concern if the output is unstable).

### CODE REVIEW

**Review by benedeki — COMMENTED** [review]
Looks good. 
But when I was looking for a way how to "release" the memory the previously used DataFrames might hold, i stumble upon this article: https://sparkbyexamples.com/spark/spark-dataframe-cache-and-persist-explained/
Wouldn't that be the solution for our case? General solution. 🤔

**Comment by dk1844** [comment]
> But when I was looking for a way how to "release" the memory the previously used DataFrames might hold, I stumbled upon this article: https://sparkbyexamples.com/spark/spark-dataframe-cache-and-persist-explained/
> Wouldn't that be the solution for our case? General solution. 🤔

Could you please _connect the dots_ for me here? Do you mean the unpersisting?

**Comment by benedeki** [comment]
> 
> 
> > But when I was looking for a way how to "release" the memory the previously used DataFrames might hold, I stumbled upon this article: https://sparkbyexamples.com/spark/spark-dataframe-cache-and-persist-explained/
> > Wouldn't that be the solution for our case? General solution. 🤔
> 
> Could you please _connect the dots_ for me here? Do you mean the unpersisting?

Well, how I understood it, using `cache()` can make the computation stable. E.g. ensure it's not recomputed, and that even if the node fails (at least under some settings).

**Comment by benedeki** [comment]
I think the release notes are too technical (developer level). I would write something like:
Switched to re-read data from disk between processing phases to ensure data stability (no change in volatile data).

**Comment by dk1844** [comment]
> Well, how I understood it, using `cache()` can make the computation stable. E.g. ensure it's not recomputed, and that even if the node fails (at least under some settings).

I don't think it solves the situation completely, but we can definitely consider that an improvement of the chances and deem it good enough. I would be content with this approach. As the linked article states:

> When you persist a dataset, each node stores it’s partitioned data in memory and reuses them in other actions on that dataset. And Spark’s persisted data on nodes are fault-tolerant meaning if any partition of a Dataset is lost, it will automatically be recomputed using the original transformations that created it.

**Review by Zejnilovic — APPROVED** [review]
Code reviewed

**Review by benedeki — APPROVED** [review]

**Pull request merged**
