### PR TITLE
713 Add favicon

### LINKED ISSUE #713: Add a favicon.ico to Menas
## Feature
Add a favicon to Menas

### PR DESCRIPTION
**Pull request by Zejnilovic**
One less 404

Fixes #713

RN: Add favicon to Menas

### CODE REVIEW

**Comment by Zejnilovic** [comment]
This is why test labels and code separation are needed. For this, we are running the whole `mvn test -Pintegration`.

**Comment by AdrianOlosutean** [comment]
Maybe it makes sense to base it on #1620

**Comment by Zejnilovic** [comment]
> Maybe it makes sense to base it on #1620

Smart. Done

**Review by AdrianOlosutean — COMMENTED** [review]
I tried it locally and the changes appear in the build, but I am not able to see the icon in the tab. Can anyone double check?

**Review by AdrianOlosutean — APPROVED** [review]
Ran it, works

**Pull request merged**
