### PR TITLE
#1909 Increase the limit of columns shown in menas column selection

### LINKED ISSUE #1909: Coalesce and Concatenation rules limit the number of columns in selection
## Describe the bug
Coalesce and Concatenation rules limit the number of columns in selection

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Have 1000 columns in a schema
2. Go to conformance rules
3. Try to add coalesce rule
4. Try to add last column

## Expected behaviour
All columns should be visible

### PR DESCRIPTION
**Pull request by Zejnilovic**
Fixes #1909 

Release Notes: Increased limit of columns shown in the selector for Coalesce and Concatenation conformance rules to 5000. This should fit most needs.

### CODE REVIEW

**Review by benedeki — APPROVED** [review]
What about declaring the 500 as a constant somewhere.

- [x] code reviewed
- [ ] pulled
- [ ] built
- [ ] run

**Comment by benedeki** [comment]
Tried it by changing the JS and veryfing the issues is gone on a Dataset the issue was reported from.

**Review by AdrianOlosutean — APPROVED** [review]

**Review by dk1844 — APPROVED** [review]
LGTM as a hotfix (just read the code). However, normally, should there rather be some sort of pagination, perhaps?

**Comment by Zejnilovic** [comment]
> LGTM as a hotfix (just read the code). However, normally, should there rather be some sort of pagination, perhaps?

Yes. That was the first idea some time ago but SapUI and time was the limitation.

**Pull request merged**
