### PR TITLE
#2118 Remove Oozie from non-model modules

### LINKED ISSUE #2118: Remove Oozie for Enceladus 3
## Background
Integrated scheduling solution doesn't make sense anymore to be part of Enceladus.

## Feature
Remove Oozie logic and references from the project

## Proposed Solution
Perhaps reference can stay in the data model, keeping it empty from now on, to avoid the need of data model change a data migration.

### LINKED ISSUE #2120: Remove Oozie from Menas (again)
## Background
We will be using a different scheduler then Oozie in the cloud.

## Feature
Remove Oozie integration from Menas (for simplicity keep in data model)

## Proposed Solution [Optional]
Solution Ideas:
1.  Look at #1428 to see what was changed on first removal

### PR DESCRIPTION
**Pull request by jakipatryk**
Removed Oozie and scheduling parts of code in all modules expect `data-model`.

### Release notes suggestion
Menas: Scheduling tab has been removed.
REST API: `/oozie/isEnabled` endpoint has been removed.
REST API: Configuration properties referencing Oozie have been removed.

Closes #2118
Closes #2120

### CODE REVIEW

**Review by Zejnilovic — COMMENTED** [review]
Oozie can still be found in:

```shell
pom.xml
175:        <oozie.version>4.3.0</oozie.version>

rest-api/pom.xml
233:            <groupId>org.apache.oozie</groupId>
234:            <artifactId>oozie-client</artifactId>
235:            <version>${oozie.version}</version>
238:                    <groupId>org.apache.oozie</groupId>
239:                    <artifactId>oozie-hadoop-auth</artifactId>
```

**Review by dk1844 — DISMISSED** [review]
LGTM except for what Sasa has already found (just checked the code)

**Comment by Zejnilovic** [comment]
Do we still need cRonstrue?

**Comment by jakipatryk** [comment]
> Do we still need cRonstrue? As far as I see, we can delete these.

@Zejnilovic yes seems it is not needed; removed

**Review by dk1844 — DISMISSED** [review]
LGTM (just read the code this time)

**Review by dk1844 — APPROVED** [review]
Still LGTM

**Comment by benedeki** [comment]
If tests are passing, that's probably good enough for know. And the complete functionality will be checked with whole _Enceladus 3_ test(s). Adding 'PR: no testing needed` label.

**Review by benedeki — COMMENTED** [review]
Could you please:
* fix the filename of `data-model/src/main/scala/za/co/absa/enceladus/model/menas/scheduler/oozie/OozIeSchedule.scala`
* Comment both remaining Oozie classes (`OozieSchedule`, `OozieScheduleInstance`), that they are kept for data model compatibility reason and to avoid the need of data migration.

Otherwise:
- [X] code reviewed
- [X] pulled
- [X] built
- [ ] run

**Comment by jakipatryk** [comment]
> Could you please:
> - fix the filename of data-model/src/main/scala/za/co/absa/enceladus/model/menas/scheduler/oozie/OozIeSchedule.scala
> - Comment both remaining Oozie classes (OozieSchedule, OozieScheduleInstance), that they are kept for data model compatibility reason and to avoid the need of data migration.

@benedeki Done

**Review by dk1844 — APPROVED** [review]

**Review by benedeki — APPROVED** [review]

**Pull request merged**
