### PR TITLE
#292 Fetch schemas for add/edit dialog via callback on press

### PR DESCRIPTION
**Pull request by GeorgiChochov**

### CODE REVIEW

**Comment by lokm01** [comment]
Can we also turn on busy indicator while we're fetching schemas? Or maybe disable the drop down?

**Comment by GeorgiChochov** [comment]
> Can we also turn on busy indicator while we're fetching schemas? Or maybe disable the drop down?

Currently it waits for the schemas to be fetched before it opens the dialog. The busy indicator made the dialog pop-up, hide and reappear on click for some reason (I think it interfered with the HDFS browser's busy indicator). I'll try to change it.

**Comment by GeorgiChochov** [comment]
> This works as intended. But I have noticed that we sent quite a lot of `CSRF: X-CSRF-TOKEN -> XXXXXX` with each click. Four with each click, to be precise. Is that normal?

Yes, we are making way too many requests (I've been keeping eye on the CSRF log as wellas an indicator of request frequency)... I'll come up with a way to reduce this. For now it's normal.

**Comment by lokm01** [comment]
LGTM

**Pull request merged**
