### PR TITLE
#549 Provide generic tools for UI5 tables

### PR DESCRIPTION
**Pull request by lokm01**
- For testing, implemented this for dataset audit trails
- If happy, we can implement on other tables as separate PRs

### CODE REVIEW

**Comment by GeorgiChochov** [comment]
Don't version and change time necessarily follow the same order?

**Comment by Zejnilovic** [comment]
> Don't version and change time necessarily follow the same order?

Good spot. I would say yes, but then again I can imagine the questions from user, why can't they sort using one or the other. I think it doesn't block anything and I would vote to keep it.

**Comment by lokm01** [comment]
1) Separate issue pls
2) You're truly killing me.... check now

**Comment by lokm01** [comment]
> Don't version and change time necessarily follow the same order?

Will super simple to change these once we merge the TableUtils I guess.

**Comment by Zejnilovic** [comment]
> 1. Separate issue pls

#571

**Pull request merged**
