### PR TITLE
1820 (Backport 2.20) Fix auditable message for Dataset Properties

### PR DESCRIPTION
**Pull request by Zejnilovic**

### CODE REVIEW

**Review by benedeki — DISMISSED** [review]
- [ ] code reviewed
- [x] pulled
- [x] built
- [x] run

**Comment by benedeki** [comment]
Quickly tried to confirm it works as in 2.22.2

**Review by dk1844 — APPROVED** [review]
LGTM (just read the code)

**Review by benedeki — DISMISSED** [review]
Well, missing new lines at the end of the scripts, but I don't care 😉

**Pull request merged**
