### PR TITLE
1145 Remove external modules

### PR DESCRIPTION
**Pull request by GeorgiChochov**

### CODE REVIEW

**Comment by Zejnilovic** [comment]
BTW this should fail on build until you create the fixed-width project

**Comment by GeorgiChochov** [comment]
> BTW this should fail on build until you create the fixed-width project

No, it can just use the latest version of the released enceladus-fixedWidth library (which has been unchanged since 1.0.0), no need to fail anything.
Not sure if I want to create a project for fixed-width at all at the moment.
Definitely not creating a project for the `kafka` module as it was dead weight.

**Comment by Zejnilovic** [comment]
Fair enough

**Comment by GeorgiChochov** [comment]
> Just so the PR is not accidentally merged before the rebase

It can't be merged, there are merge conflicts, but thanks.

**Pull request merged**
