### PR TITLE
#515 Resolve security alerts in npm

### PR DESCRIPTION
**Pull request by lokm01**
- here npm-shrinkwrap replaces package-lock.json

Signed-off-by: Jan Scherbaum <kmoj02@gmail.com>

### CODE REVIEW

**Comment by Zejnilovic** [comment]
I just saw that your `npm-shrinkwrap.json` differs from mine after the build. Does anyone else have this?

**Comment by GeorgiChochov** [comment]
> npm-shrinkwrap.json

Yep, "mime" dependency is reordered on mine as well.

**Comment by GeorgiChochov** [comment]
How does this resolve security alerts?

**Comment by lokm01** [comment]
> How does this resolve security alerts?

Upgraded grunt as a top level dependency and mime versions as transitive dependencies.

**Comment by lokm01** [comment]
image

**Pull request merged**
